# SPDX-License-Identifier: Apache-2.0

manifest:
  defaults:
    remote: zephyrproject-rtos

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: fwatch
      url-base: https://gitee.com/fwatch

  projects:
    - name: zephyr
      remote: fwatch
      west-commands: scripts/west-commands.yml
      revision: main
      import:
        name-allowlist:
          - cmsis_6
          - hal_nordic
          - hal_sifli

  self:
    path: pinetime
