# SPDX-License-Identifier: Apache-2.0

manifest:
  defaults:
    remote: zephyrproject-rtos

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  # External projects
  #
  projects:
    - name: cmsis
      path: modules/hal/cmsis
      revision: b0612c97c1401feeb4160add6462c3627fe90fc7
    - name: hal_nordic
      path: modules/hal/nordic
      revision: a6e5299041f152da5ae0ab17b2e44e088bb96d6d
    - name: lvgl
      path: modules/lib/gui/lvgl
      revision: 783c1f78c8e39751fe89d0883c8bce7336f55e94
    - name: segger
      path: modules/debug/segger
      revision: 3a52ab222133193802d3c3b4d21730b9b1f1d2f6
    - name: tinycrypt
      path: modules/crypto/tinycrypt
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
    - name: zephyr
      west-commands: scripts/west-commands.yml
      revision: main
  self:
    path: app
