#pragma once

#include "graphics.h"

/**
 * Data Structure
 */
typedef n_GBitmapDataRowInfo GBitmapDataRowInfo;
typedef n_EdgeInsets EdgeInsets
typedef n_GPoint GPoint;
typedef n_GRect GRect;
typedef n_GSize GSize;

typedef n_GColor GColor;
typedef GBitmap GBitmap;
typedef n_GBitmapSequence GBitmapSequence;
typedef n_GContext GContext;

#define GPointZero n_GPointZero
#define GSizeZero n_GSizeZero
#define GRectZero n_GRectZero

/*
GColorFromRGBA
GColorFromRGB
GColorFromHEX
COLOR_FALLBACK
PBL_IF_RECT_ELSE
PBL_IF_ROUND_ELSE
PBL_IF_BW_ELSE
PBL_IF_COLOR_ELSE



PLAY_COUNT_INFINITE
PLAY_DURATION_INFINITE
GEdgeInsets4
GEdgeInsets3
GEdgeInsets2
GEdgeInsets1
GEdgeInsetsN
GEdgeInsets
*/
#define gcolor_equal n_gcolor_equal
#define gcolor_legible_over n_gcolor_legible_over
#define gpoint_equal gpoint_equal n_gpoint_equal gpoint_equal
#define gsize_equal gsize_equal n_gsize_equal gsize_equal
#define grect_equal grect_equal n_grect_equal grect_equal
#define grect_is_empty n_grect_is_empty
#define grect_standardize n_grect_standardize
#define grect_clip n_grect_clip
#define grect_contains_point n_grect_contains_point
#define grect_center_point n_grect_center_point
#define grect_crop n_grect_crop
#define gbitmap_get_bytes_per_row n_gbitmap_get_bytes_per_row
#define gbitmap_get_format n_gbitmap_get_format
#define gbitmap_get_data n_gbitmap_get_data
#define gbitmap_set_data n_gbitmap_set_data
#define gbitmap_get_bounds n_gbitmap_get_bounds
#define gbitmap_set_bounds n_gbitmap_set_bounds
#define gbitmap_get_palette n_gbitmap_get_palette
#define gbitmap_set_palette n_gbitmap_set_palette
#define gbitmap_create_with_resource n_gbitmap_create_with_resource
#define gbitmap_create_with_data n_gbitmap_create_with_data
#define gbitmap_create_as_sub_bitmap n_gbitmap_create_as_sub_bitmap
#define gbitmap_create_from_png_data n_gbitmap_create_from_png_data
#define gbitmap_create_blank n_gbitmap_create_blank
#define gbitmap_create_blank_with_palette n_gbitmap_create_blank_with_palette
#define gbitmap_create_palettized_from_1bit n_gbitmap_create_palettized_from_1bit
#define gbitmap_destroy n_gbitmap_destroy
#define gbitmap_sequence_create_with_resource n_gbitmap_sequence_create_with_resource
#define gbitmap_sequence_update_bitmap_next_frame n_gbitmap_sequence_update_bitmap_next_frame
#define gbitmap_sequence_update_bitmap_by_elapsed n_gbitmap_sequence_update_bitmap_by_elapsed
#define gbitmap_sequence_destroy n_gbitmap_sequence_destroy
#define gbitmap_sequence_restart n_gbitmap_sequence_restart
#define gbitmap_sequence_get_current_frame_idx n_gbitmap_sequence_get_current_frame_idx
#define gbitmap_sequence_get_total_num_frames n_gbitmap_sequence_get_total_num_frames
#define gbitmap_sequence_get_play_count n_gbitmap_sequence_get_play_count
#define gbitmap_sequence_set_play_count n_gbitmap_sequence_set_play_count
#define gbitmap_sequence_get_bitmap_size n_gbitmap_sequence_get_bitmap_size
#define gbitmap_get_data_row_info n_gbitmap_get_data_row_info
#define grect_align n_grect_align
#define grect_inset n_grect_inset