#pragma once

#include "graphics.h"

#define graphics_draw_pixel n_graphics_draw_pixel
#define graphics_draw_line n_graphics_draw_line
#define graphics_draw_rect n_graphics_draw_rect
#define graphics_fill_rect n_graphics_fill_rect
#define graphics_draw_circle n_graphics_draw_circle
#define graphics_fill_circle n_graphics_fill_circle
#define graphics_draw_round_rect n_graphics_draw_round_rect
#define graphics_draw_bitmap_in_rect n_graphics_draw_bitmap_in_rect
#define graphics_capture_frame_buffer n_graphics_capture_frame_buffer
#define graphics_capture_frame_buffer_format n_graphics_capture_frame_buffer_format
#define graphics_release_frame_buffer n_graphics_release_frame_buffer
#define graphics_frame_buffer_is_captured n_graphics_frame_buffer_is_captured
#define graphics_draw_rotated_bitmap n_graphics_draw_rotated_bitmap
#define graphics_draw_arc n_graphics_draw_arc
#define graphics_fill_radial n_graphics_fill_radial
#define gpoint_from_polar n_gpoint_from_polar
#define grect_centered_from_polar n_grect_centered_from_polar