#pragma once

#include "graphics.h"

typedef n_GTextOverflowMode GTextOverflowMode;
typedef n_GTextAlignment GTextAlignment;

typedef n_GTextAttributes GTextAttributes;

#define graphics_text_attributes_create n_graphics_text_attributes_create
#define graphics_text_attributes_destroy n_graphics_text_attributes_destroy
#define graphics_text_attributes_restore_default_text_flow n_graphics_text_attributes_restore_default_text_flow
#define graphics_text_attributes_enable_screen_text_flow n_graphics_text_attributes_enable_screen_text_flow
#define graphics_text_attributes_restore_default_paging n_graphics_text_attributes_restore_default_paging
#define graphics_text_attributes_enable_paging n_graphics_text_attributes_enable_paging
#define graphics_draw_text n_graphics_draw_text
#define graphics_text_layout_get_content_size n_graphics_text_layout_get_content_size
#define graphics_text_layout_get_content_size_with_attributes n_graphics_text_layout_get_content_size_with_attributes