#pragma once

#include "graphics.h"

#define graphics_context_set_stroke_color graphics_context_set_stroke_color
#define graphics_context_set_fill_color graphics_context_set_fill_color
#define graphics_context_set_text_color graphics_context_set_text_color
#define graphics_context_set_compositing_mode graphics_context_set_compositing_mode
#define graphics_context_set_antialiased graphics_context_set_antialiased
#define graphics_context_set_stroke_width graphics_context_set_stroke_width